config/routes.rb
Confessional::Application.routes.draw do
  resources :comments, only: [:create]
  resources :confessions, only: [:create, :show, :index]

  resources :confessions do
    resources :comments
   end

  root :to => 'confessions#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :confession

  validates :content, presence: true

end

app/models/confession.rb
class Confession < ActiveRecord::Base
  attr_accessible :content, :updated_at
  has_many :comments, dependent: :destroy

  validates :content, presence: true, uniqueness: true
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :last_seen_at, :uuid
  
#  validates :uuid, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @confession = Confession.find(params[:confession_id])
    @comment = @confession.comments.build(params[:comment])
    
    @comment_count = @confession.comments.count + 1
    @comment_count_html = "<h3 id='reactions-heading'>Reactions (#{@comment_count})</h3>"
    
    if @comment.save
      Pusher['confession-channel'].trigger('new-comment-event', 
        {:confession_id => @comment.confession_id,
        :comment => render_to_string(@comment, locals: {count: @comment_count}),
        :comment_count => @comment_count_html})
        
      @confession.update_attributes(updated_at: Time.now)
      redirect_to "/confessions/#{@confession.id}/##{@confession.comments.count}"
    else
      redirect_to "/confessions/#{@confession.id}/"
    end
  end
end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController
  before_filter :get_session, only: [:index, :show, :create]
  
  # GET /confessions
  # GET /confessions.json
  def index
    @confessions = Confession.paginate(page: params[:page], per_page: 10, order: "updated_at DESC")
    @confession = Confession.new(params[:confession])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @confessions }
    end
  end

  # GET /confessions/1
  # GET /confessions/1.json
  def show
    @confession = Confession.find(params[:id])
    @comments = @confession.comments
    @comment = Comment.new(params[:confession])
  end

  # POST /confessions
  # POST /confessions.json
  def create
    @confession = Confession.new(params[:confession])
    @confessions = Confession.paginate(page: params[:page], per_page: 10, order: "created_at DESC")
    
    if @confession.save
      flash[:success] = "Confession commiserated!"
      Pusher['confession-channel'].trigger('new-confession-event', 
        {:confession => render_to_string(@confession)})
      redirect_to root_path
    else
      render "index"
    end
  end

  # DELETE /confessions/1
  # DELETE /confessions/1.json
  def destroy
    @confession = Confession.find(params[:id])
    @confession.destroy

    respond_to do |format|
      format.html { redirect_to confessions_url }
      format.json { head :no_content }
    end
  end
  
  private
    def get_session
      if session[:uuid].blank?
        @session = Session.create
        @session.last_seen_at =  Time.new
        @session.save
        session[:uuid] = @session.id
      else
        @session = Session.find_by_id(session[:uuid])
        @session.last_seen_at = Time.new
        @session.save
      end

      @session_count = Session.find(:all, conditions: ['last_seen_at > ?', 5.minutes.ago]).count
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_pusher_key
  	if Rails.env.production?
  	  return "'a3858e72333922ce04f6'"
  	else
      return "'3959abe8b63fee2973a9'"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def add_comment_number_links(comment)
    regex = /#[0-9]+/
    comment.sub(regex) { |match| "<a href = #{match}>#{match}</a>" }.html_safe
  end
  
  def escape_chars
  end
end

app/helpers/confessions_helper.rb
module ConfessionsHelper
end

app/views/comments/_comment.html.erb
<li>
	<span class="terminal-chars">&gt;&gt;&nbsp;</span>
  <span class="comment-content" id="<%= comment.id %>"></span>
  <span class="comment-content" id="<%= (defined? comment_counter).nil? ? count : comment_counter + 1 %>"><%= add_comment_number_links(h(comment.content)) %></span>
  <div class="comment-details">
	  <span class="timestamp">
	    <i class="icon-time"></i> <%= comment.created_at.in_time_zone("Eastern Time (US & Canada)").to_formatted_s(:long_ordinal) %>
	  </span>
    <span class="comment-number">#<%= (defined? comment_counter).nil? ? count : comment_counter + 1 %></span>
  </div>
  <div style="clear:both;"></div>
</li>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :confession_id %><br />
    <%= f.number_field :confession_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Confession</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.content %></td>
    <td><%= comment.confession_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Confession:</b>
  <%= @comment.confession_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/confessions/_comment_form.html.erb
<%= form_for([confession, @comment]) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <h3>Reply</h3>
    <%= f.text_area :content, placeholder: "Type your reaction here..." %>
  </div>
  <%= f.submit "Reply", class: "btn-large myButton" %>
  <span id="comment-tip">
  	tip: enter '#1' to link to comments<br>(and you can no longer hack us :P)
  </span>	
<% end %>

app/views/confessions/_confession.html.erb
<div class="confession">
  <span class="confession-content"><%= confession.content %></span>
  <div class="confession-details">
    <span class="confession-link">
      <%= link_to(confession) do %>
        <i class="icon-comment"></i> <%= pluralize(confession.comments.count, 'reaction') %>
      <% end %>
    </span>
    <span class="timestamp">
      <i class="icon-time"></i> <%= confession.created_at.in_time_zone("Eastern Time (US & Canada)").to_formatted_s(:long_ordinal) %>
    </span>
    <div style="clear:both;"></div>
  </div>
</div>

app/views/confessions/_confession_form.html.erb
<%= form_for(@confession) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <h3>Anonymous Confession</h3>
    <%= f.text_area :content, placeholder: "Type a confession here..." %>
  </div>
  <%= f.submit "Enter the Booth", class: "btn-large myButton" %>
<% end %> 

app/views/confessions/_form.html.erb
<%= form_for(@confession) do |f| %>
  <% if @confession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@confession.errors.count, "error") %> prohibited this confession from being saved:</h2>

      <ul>
      <% @confession.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/confessions/edit.html.erb
<h1>Editing confession</h1>

<%= render 'form' %>

<%= link_to 'Show', @confession %> |
<%= link_to 'Back', confessions_path %>

app/views/confessions/index.html.erb
<div id="below-title">
  <aside id="confession">
    <section>
      <%= render "confession_form" %>
    </section>
  </aside>

  <div id="confessions">
    <h3 id="confessions-title">Latest Secrets &amp;<br>Reactions</h3>
    <%= render @confessions %>
  </div>
  <div style="clear:both;"></div>
  <%= will_paginate %>
</div>

<script type="text/javascript">
  var pusher = new Pusher(<%= render_pusher_key %>);
  var channel = pusher.subscribe('confession-channel');
  channel.bind('new-confession-event', function(data) {
    $(data.confession).css('display','none').addClass('new-push').insertBefore('#confessions div:first').slideDown();
  });
</script>

app/views/confessions/new.html.erb
<h1>New confession</h1>

<%= render 'form' %>

<%= link_to 'Back', confessions_path %>

app/views/confessions/show.html.erb
<div class="row">
  <div id="confession">
    <span id="confession-content"><%= @confession.content %></span>
  </div>
  <div id="below-confession">
    <aside id="comment">
      <section>
        <%= render "comment_form", confession: @confession %>
      </section>
    </aside>

    <div id="comments">
      <h3 id="reactions-heading">Reactions (<%= @confession.comments.count %>)</h3>
      <ol class="comments">
        <li style="display:none;"></li>
        <%= render @comments %>
      </ol>
    </div>
  </div>
</div>

<script type="text/javascript">
  var pusher = new Pusher(<%= render_pusher_key %>);
  var channel = pusher.subscribe('confession-channel');
  channel.bind('new-comment-event', function(data) {
    if (data.confession_id == <%= @confession.id %>)
    {
      $(data.comment).css('display','none').addClass('new-push').insertAfter('ol.comments li:last').slideDown();
      $('h3#reactions-heading').replaceWith(data.comment_count);
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>the VU koor confessional</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
  <script type="text/javascript" src="https://d3dy5gmtp8yhk7.cloudfront.net/1.12/pusher.min.js"></script>
  <link rel="shortcut icon" href="favicon.ico"/>
</head>
<body>
  <div id="counter">
    <%= pluralize(@session_count, 'sinner') + " in the booth" %>
  </div>
  <div id="wrapper" class="center">
    <h1>
      <%= link_to(confessions_path) do %>
        $ the VU koor confessional<span class="blink cursor">&nbsp;</span>
      <% end %>
    </h1>

<%= yield %>

  </div>

  <script type="text/javascript" language="javascript">
    $(document).ready(function()
    {
      $('.blink').blink(); // default is 500ms blink interval.
    });
  </script>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>